<?php

/**
 * @file
 * Implements hooks that get tested by islandora_hooks.test
 */

/**
 * Implements hook menu.
 */
function islandora_solr_ingest_test_menu() {
  return array(
    'test/solr/ingest' => array(
      'title' => 'Ingest Form',
      'page callback' => 'islandora_solr_ingest_test_ingest',
      'type' => MENU_LOCAL_ACTION,
      'access callback' => TRUE,
    ),
  );
}

/**
 * Render the ingest form.
 */
function islandora_solr_ingest_test_ingest() {
  $connection = islandora_get_tuque_connection();
  $object = $connection->repository->constructObject('test' . random_string() . ':test' . random_string());
  $object->label = 'New Object';
  $configuration = array(
    'objects' => array($object),
  );
  module_load_include('inc', 'islandora', 'includes/ingest.form');
  return drupal_get_form('islandora_ingest_form', $configuration);
}

/**
 * Generate random string for pid.
 *
 * @param int $length
 *   The length of the string to generate.
 *
 * @return string
 *   Random string generated.
 */
function random_string($length = 8) {
  $key = '';
  $keys = array_merge(range(0, 9), range('a', 'z'), range('A', 'Z'));

  for ($i = 0; $i < $length; $i++) {
    $key .= $keys[array_rand($keys)];
  }

  return $key;
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_solr_ingest_test_islandora_ingest_steps(array &$form_state) {
  return array(
    'islandora_ingest_test' => array(
      'type' => 'form',
      'form_id' => 'islandora_solr_ingest_test_set_label_form',
      'weight' => -50,
      'module' => 'islandora_ingest_test',
    ),
  );
}

/**
 * Sets the label of the ingestable object.
 *
 * @param array $form
 *   The Drupal form.
 * @param array $form_state
 *   The Drupal form state.
 *
 * @return array
 *   The Drupal form definition.
 */
function islandora_solr_ingest_test_set_label_form(array $form, array &$form_state) {
  $models = array(
    'test:testcmodel',
  );
  $model = isset($form_state['values']['model']) ? $form_state['values']['model'] : reset($models);
  $shared_storage = &islandora_ingest_form_get_shared_storage($form_state);
  $shared_storage['models'] = array($model);
  return array(
    '#prefix' => '<div id="islandora-select-content-model-wrapper">',
    '#suffix' => '</div>',
    'label' => array(
      '#type' => 'textfield',
      '#title' => t('Label'),
    ),
    'model' => array(
      '#type' => 'select',
      '#title' => t('Select a Content Model to Ingest'),
      '#options' => array_combine($models, $models),
      '#default' => $model,
      '#ajax' => array(
        'callback' => 'islandora_solr_ingest_test_model_ajax_callback',
        'wrapper' => 'islandora-select-content-model-wrapper',
        'method' => 'replace',
        'effect' => 'fade',
      ),
    ),
  );
}

/**
 * Updates the model field.
 */
function islandora_solr_ingest_test_model_ajax_callback(array $form, array &$form_state) {
  return $form;
}

/**
 * Sets the label of the ingestable object.
 *
 * @param array $form
 *   The Drupal form.
 * @param array $form_state
 *   The Drupal form state.
 */
function islandora_solr_ingest_test_set_label_form_submit(array $form, array &$form_state) {
  $object = islandora_ingest_form_get_object($form_state);
  $object->label = $form_state['values']['label'];
  unset($object->models);
  $object->models = array($form_state['values']['model']);
}
